### ISSUE TITLE
Overlapping Windmill Entities

### ISSUE THREAD

**Issue by kMaiSmith** [Aroma1997/CompactWindmills#21]
I have very little context to figure out why this is happening let alone how to reproduce it, but this appears to frequently spam my chat.  I would speculate that it is when a player moves near a windmill thus loading the chunk.

Here's a dump of all information i can find about this issue:

13:34:49 [WARNING] EnergyNet.addTileEntity:
aroma1997.compactwindmills.TileEntityLV@5b1a57 (aroma1997.compactwindmills.TileEntityLV@5b1a57) is conflicting with aroma1997.compactwindmills.TileEntityLV@3267753b using the same position (already added, prev. te not removed, overlapping), aborting

**Comment by kMaiSmith** [comment]
I will look into getting this fixed, just thought i should submit an issue to keep it tracked.

**Comment by Aroma1997** [comment]
What version are you using?

**Comment by kMaiSmith** [comment]
I am currently using version 4.4.19.224 which is shipped with the FTB pack Techworld 2 version 1.1.2

**Comment by kMaiSmith** [comment]
I sent you a request on the minecraft forum for a deobfuscated version of Aroma1997-core

**Comment by Aroma1997** [comment]
Answered it

**Comment by kMaiSmith** [comment]
Much to my chagrin, my investigation has lead me to conclude that this issue is just garbage logging from IndustrialCraft 2 rather than an issue with Compact Windmills.  It looks as if this is just an issue with poor data management with the IC2 mod.  Thank you.
