### ISSUE TITLE
Render Distance

### ISSUE THREAD

**Issue by xeedness** [Aroma1997/CompactWindmills#25]
Hello there,
can you please make the render distance of your windmill dynamic and increase to the max render distance setting. You got a great visual effect there, but it doesn't give any good, when it is not being rendered, if you place it too high.

**Comment by Aroma1997** [comment]
There is no way I can do that, the rotor gets rendered, when the Windmill as a TileEntity would be rendered.

**Comment by xeedness** [comment]
Well, the block does get rendered, but the rotor isn't

**Comment by xeedness** [comment]
public class TileEntity
{
....
@SideOnly(Side.CLIENT)
    public double getMaxRenderDistanceSquared()
    {
        return 4096.0D;
    }
...
}

This could be it. obviously it is fixed. I just messured it. The rotor does have exactly a render distance of 64 blocks. While the block exceeds that amount dynamically.

**Comment by Aroma1997** [comment]
Yes, the block gets rendered, ecause I render the block as a normal block, but the Rotor as a TileEntity-block.
