### ISSUE TITLE
[BUG] Rotors not craftable in CW 1.0.2.3

### ISSUE THREAD

**Issue by iLLHunter** [Aroma1997/CompactWindmills#32]
None of the rotors have recipes in NEI in version 1.0.2.3

I found an ftbwiki (http://ftbwiki.org/Carbon_Rotor) page that listed recipes and tried those; carbon plate around basic casing does not craft carbon rotor nor does or adv alloy craft an alloy rotor. 4 sticks around iron plate does not craft wood rotor.

These did not work in my "pack" so I loaded only CW and IC2, same issue.

CW 1.0.2.3
IC2 2.0.397
Minecraft 1.6.4

**Comment by Aroma1997** [comment]
This happens, when the setting for requiring rotors is turned off!

**Comment by iLLHunter** [comment]
What setting is this? I have IC2 stuff set to True (the default)

http://paste.ubuntu.com/7814658/

What is incorrect in this config?
