### ISSUE TITLE
[BUG] Rotors not craftable in CW 1.0.2.3

### ISSUE THREAD

**Issue by iLLHunter** [Aroma1997/CompactWindmills#33]
Last issue was closed prematurely, and users do not have option to re-open

None of the rotors have recipes in NEI in version 1.0.2.3

I found an ftbwiki (http://ftbwiki.org/Carbon_Rotor) page that listed recipes and tried those; carbon plate around basic casing does not craft carbon rotor nor does or adv alloy craft an alloy rotor. 4 sticks around iron plate does not craft wood rotor.

These did not work in my "pack" so I loaded only CW and IC2, same issue.

CW 1.0.2.3
IC2 2.0.397
Minecraft 1.6.4

You mentioned a setting. I am using IC2 stuff (True) in the config, so it uses the advanced alloy, basic machine casing, etc.

What setting am I missing?

http://paste.ubuntu.com/7814658/

What is incorrect in this config?

**Comment by Aroma1997** [comment]
It is NOT a bug, if you want to have the rotors (and use them), you have to disable useIC2Stuff.

**Comment by iLLHunter** [comment]
Oh I see the confusion. You have true and false backwards. True in this sense means to allow or to use something. False means to not allow or to not use something.

You are saying if I set useIC2Stuff to false, then the mod will use the IC2 stuff; basic casing, advanced alloy, etc, to craft the rotor recipes.
If I leave useIC2Stuff set to True, then the mod will not use IC2stuff.

This is backwards. The setting should either be switched, so that False does not use IC2 stuff and True does, or change the setting name to something like disableIC2Stuff, so that True will disable and false will not disable.

**Comment by Aroma1997** [comment]
No, you got it the other way around, it is NOT backwards, if it is set to true, the compact windmills will be like the normal IC2 windmills (wind strength and not requiring rotors, that's why it's called useIC2stuff) and if it is set to false, it will change its behaviour to be NOT like IC2's windmills(requiring rotors, not having wind strength,...)!

**Comment by iLLHunter** [comment]
I guess it's the "useIC2stuff" that is confusing. "Stuff" implies using IC2 components like advanced alloy, basic machine casing, etc. 

"useIC2mode" "IC2method" "IC2style" or something more precise besides "stuff" may help eliminate the confusion.

**Comment by iLLHunter** [comment]
thanks for your help and explanation of what you meant

**Comment by Aroma1997** [comment]
That is true, but if i change it, it will break many config files...

**Comment by iLLHunter** [comment]
If you plan it for the next version, it wont break what is already working on peoples servers.

The next release of the mod can be a "breaking update". I see developers put messages like that in their MCF posts to let people know. You could even choose to change the minor or major version number so people know they can not add to existing worlds. like 1.1.0. Putting a message in MCF post is probably sufficient.

This way any existing servers will continue to use what they have and only use the fixed version on new servers. Nothing will break on people so everyone should be happy.

Just a suggestion

**Comment by Aroma1997** [comment]
I won't change the major version number just to change a config key.
I won't change the config key, because 99.9% of the people using CW were able to find out, what I mean with that.
