### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by kevinkjt2000** [Aroma1997/CompactWindmills#39]
I am having trouble building this mod from source.  I cloned the repo, downloaded AromaCore-1.0.2.8 and put it in a libs folder I created, and then ran "gradlew.bat build".  That is when I saw this:
https://gist.github.com/kevinkjt2000/62c2749cbde073883d6f
Any suggestions on how to fix this?  Unfortunately I have no idea what func_70302_i_ is supposed to do even after trying to search around for it.  About all I can gather is that the function is needed for tile entities to work.

**Comment by Aroma1997** [comment]
You have to download the deofuscated version.
(Dowload link if you're too lazy to google it: https://www.dropbox.com/sh/8oufghny1c3avh8/AADNJ5KeYnhnTYWb4m4czSMaa/aroma1997core/version?dl=0 )
