### ISSUE TITLE
mcmod.info is not valid JSON

### ISSUE THREAD

**Issue by shartte** [Aroma1997/CompactWindmills#4]
The trailing comma is invalid (see here: http://jsonlint.com/)

**Comment by Aroma1997** [comment]
You don't need the comma

**Comment by shartte** [comment]
Yes. That's why i removed it in my pull request ;-)

Having it makes the JSON invalid.

**Comment by Aroma1997** [comment]
Sorry I got it the other way around...

**Comment by shartte** [comment]
Not a problem :)

**Comment by Aroma1997** [comment]
Ok merged...

**Comment by Aroma1997** [comment]
... there is no comma...

**Comment by shartte** [comment]
Well yes, thanks for merging :+1: :)
