### ISSUE TITLE
crash on 1.7.10

### ISSUE THREAD

**Issue by samstone86** [Aroma1997/CompactWindmills#40]
on 1.7.10 compact windmills crashes with ic2 error

java.lang.AbstractMethodError: aroma1997.compactwindmills.TileEntityEV.getSourceTier()I

any news on a 1.7.10 version?

**Comment by Aroma1997** [comment]
No 1.7.10 version out yet, so no crash.

**Comment by samstone86** [comment]
The 1.7.2 crashes in 1.7.10 when placeing a windmill
Am 17.10.2014 15:56 schrieb "Aroma1997" notifications@github.com:

**Comment by Aroma1997** [comment]
Maybe it crashes, because the 1.7.2 version is meant for use for 1.7.2 and not for 1.7.10?

**Comment by samstone86** [comment]
Could be :-) any plans for 1.7.10 ? I try to collect all mods Form
Techworld 2 for 1.7.10 .
Am 17.10.2014 21:54 schrieb "Aroma1997" notifications@github.com:

**Comment by Aroma1997** [comment]
That was a rhetorical question... :-|
