### ISSUE TITLE
Localization support

### ISSUE THREAD

**Issue by Vexatos** [Aroma1997/CompactWindmills#6]
I really would like to see this mod supporting localizations.

**Comment by Aroma1997** [comment]
I'm not sure if I will implement that in the near future, but that time when I implement that will DEFINITELY hit!

**Comment by ghost** [comment]
As i know, you can easy add localization to lang file just writing item like item.<itemname> = "blablabla"

**Comment by Aroma1997** [comment]
When I'm done with the other stuff I want to do, I'll do that.
I know how to do that, but it's just a pain.

**Comment by Aroma1997** [comment]
Done
