### ISSUE TITLE
UseIC2Stuff config option still requires rotors

### ISSUE THREAD

**Issue by ianc1215** [Aroma1997/CompactWindmills#7]
I am running CompactWindmills on a server using IC2 Experimental Build# 254. When I set the configuration option "UseIC2Stuff=true" The windmills still require rotors but the rotor are uncraftable in the workbench. If no rotor is inserted the GUI reads 0 EU/t.

**Comment by Aroma1997** [comment]
Does it output energy in a nearby MFSU for example?

**Comment by ianc1215** [comment]
Nope. The Windmill is dead in the water.

**Comment by Aroma1997** [comment]
Could not reproduce it.

**Comment by Aroma1997** [comment]
From what I can see from #14 it works.
